# Dockerfile: Defines container specifications to startup and run.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore

# Use the official alpine image as a base:
FROM alpine:3.19.1

# Download and install TFTP server:
RUN apk add --no-cache tftp-hpa supervisor

# Create a directory to store the files:
RUN mkdir -p /tftpshare
RUN mkdir -p /var/log/supervisor /etc/supervisor/conf.d

COPY ./supervisor-TFTP.conf /etc/supervisord.conf

# Start the TFTP server and keep it running:
CMD ["supervisord", "-c", "/etc/supervisord.conf"]